apiVersion: v1
kind: Secret
metadata:
  name: netobserv-loki-store-minio-secret
  namespace: netobserv   
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucketnames: netobserv-loki-store
  endpoint: https://minio-api-minio.apps.cluster-njsll.njsll.sandbox2550.opentlc.com
  region: eu-central-1